org: deveesistemas
app: foodiary-backend
service: backend

provider:
  name: aws
  runtime: nodejs22.x
  region: sa-east-1
  architecture: arm64
  timeout: 60
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    PASSWORD_HASH_SALT: ${env:PASSWORD_HASH_SALT}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    OPENAI_SECRET_KEY: ${env:OPENAI_SECRET_KEY}

plugins:
  - serverless-offline

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foodiary-api-uploads

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST

  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          path: /me
          method: GET

  createMeal:
    handler: src/functions/create-meal.handler
    events:
      - httpApi:
          path: /meals
          method: POST

  listMeals:
    handler: src/functions/list-meals.handler
    events:
      - httpApi:
          path: /meals
          method: GET

  getMealById:
    handler: src/functions/get-meal-by-id.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: GET